# -*- coding: utf-8 -*-
#cambios para poder hacer commit
{
    'name': 'Cotizador2',
    'version': '5.1.0',
    'category': 'Sales',
    'summary': 'Cotizador2',
    'sequence': -101,
    'description': """Modulo cotizador desarrollado para Borintech""",
    'author': 'Devman - Matias Banega',
    'maintainer': 'Devman - Matias Banega',
    'website': 'https://www.devman.com.ar',
    'license': 'AGPL-3',
    'depends': ['base', 'sale', 'sale_management', 'stock', 'purchase'],
    'data': [
        'views/costos_almacenamiento.xml',
        # 'views/analitico.xml',
        'views/cotizador.xml',
        'views/configuracion.xml',
        'views/bobinas.xml',
        'views/cajas.xml',
        'views/utilidad.xml',
        'views/cotizador_page_cajas.xml',
        'security/cotizador_security.xml',
        'security/ir.model.access.csv',
            ],
    'demo': [],
    'qweb': [],
    'images': ['static/src/img/cogs.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
